#!/usr/bin/env python3

with open('core/flow_controller.py', 'r') as f:
    lines = f.readlines()

# Find the line with the generate_target_events_recommendation method definition
start_line = None
for i, line in enumerate(lines):
    if "async def generate_target_events_recommendation" in line:
        start_line = i
        break

if start_line is not None:
    # Create the new implementation
    new_implementation = [
        "    async def generate_target_events_recommendation(self):\n",
        "        \"\"\"Generate a recommendation for target events based on business profile and goals.\"\"\"\n",
        "        try:\n",
        "            # If we have website analysis results with UI data, use that\n",
        "            if (hasattr(self, 'website_analysis_results') and \n",
        "                self.website_analysis_results and \n",
        "                'ui_data' in self.website_analysis_results):\n",
        "                \n",
        "                ui_data = self.website_analysis_results['ui_data']\n",
        "                \n",
        "                # Extract event strategies from UI data\n",
        "                if 'event_strategies' in ui_data:\n",
        "                    strategies = ui_data['event_strategies']\n",
        "                    \n",
        "                    # Build formatted response from structured data\n",
        "                    response_parts = []\n",
        "                    \n",
        "                    # Add who to target section\n",
        "                    if 'who_to_target' in ui_data:\n",
        "                        response_parts.append(\"WHO TO TARGET:\")\n",
        "                        for target in ui_data['who_to_target']:\n",
        "                            response_parts.append(f\"• {target.get('group_title', '')}: {target.get('group_detail', '')}\")\n",
        "                        response_parts.append(\"\")\n",
        "                    \n",
        "                    # Add goal-specific strategies\n",
        "                    for goal_key, strategy in strategies.items():\n",
        "                        if isinstance(strategy, dict) and 'goal_title' in strategy:\n",
        "                            response_parts.append(f\"{strategy['goal_title']}:\")\n",
        "                            \n",
        "                            # Handle the new simplified format with 'strategy' field\n",
        "                            if 'strategy' in strategy:\n",
        "                                response_parts.append(f\"• {strategy['strategy']}\")\n",
        "                            # Fallback to old format with 'event_types' if present\n",
        "                            elif 'event_types' in strategy:\n",
        "                                for event_type in strategy['event_types']:\n",
        "                                    if isinstance(event_type, dict):\n",
        "                                        response_parts.append(f\"• {event_type.get('type_title', '')}\")\n",
        "                                        response_parts.append(f\"  {event_type.get('why_works', '')}\")\n",
        "                            response_parts.append(\"\")\n",
        "                    \n",
        "                    # Store the formatted text for backward compatibility\n",
        "                    self.target_events_text = \"\\n\".join(response_parts)\n",
        "                    \n",
        "                    # Return the full UI data structure\n",
        "                    return ui_data\n",
        "            \n",
        "            # Fallback to basic recommendation if no structured data\n",
        "            primary_goal = self.primary_goal if hasattr(self, 'primary_goal') else \"\"\n",
        "            if not primary_goal and hasattr(self, 'selected_goals') and self.selected_goals:\n",
        "                primary_goal = self.selected_goals[0]\n",
        "            \n",
        "            # Create fallback UI data structure based on primary goal\n",
        "            fallback_text = \"\"\n",
        "            if primary_goal == \"find_buyers\":\n",
        "                fallback_text = \"Based on your goal of finding buyers, we recommend focusing on industry-specific trade shows and conferences where potential customers gather.\"\n",
        "            elif primary_goal == \"recruit_talent\": \n",
        "                fallback_text = \"For recruiting talent, we recommend targeting tech job fairs, university career events, and industry-specific networking meetups.\"\n",
        "            elif primary_goal == \"business_partners\":\n",
        "                fallback_text = \"To find business partners, focus on industry conferences, partnership-focused events, and ecosystem gatherings.\"\n",
        "            elif primary_goal == \"investors\":\n",
        "                fallback_text = \"For connecting with investors, target startup pitch events, investor showcases, and industry-specific venture capital gatherings.\"\n",
        "            else:\n",
        "                fallback_text = \"We recommend focusing on industry-specific events where you can connect with potential customers, partners, and talent.\"\n",
        "            \n",
        "            # Store the fallback text for backward compatibility\n",
        "            self.target_events_text = fallback_text\n",
        "            \n",
        "            # Create a minimal UI data structure with the fallback text\n",
        "            fallback_ui_data = {\n",
        "                \"target_events_text\": fallback_text,\n",
        "                \"who_to_target\": [\n",
        "                    {\"group_title\": \"Industry Professionals\", \"group_detail\": \"Focus on decision-makers in your target market\"},\n",
        "                    {\"group_title\": \"Potential Customers\", \"group_detail\": \"Connect with individuals who have a need for your product or service\"}\n",
        "                ],\n",
        "                \"event_strategies\": {\n",
        "                    \"find_buyers\": {\n",
        "                        \"goal_title\": \"For Finding Buyers/Users\",\n",
        "                        \"goal_icon\": \"💰\",\n",
        "                        \"strategy\": \"Attend industry-specific trade shows and conferences where potential customers gather.\"\n",
        "                    },\n",
        "                    \"business_partners\": {\n",
        "                        \"goal_title\": \"For Meeting Business Partners\",\n",
        "                        \"goal_icon\": \"🤝\",\n",
        "                        \"strategy\": \"Participate in conferences and integration events to connect with potential partners.\"\n",
        "                    },\n",
        "                    \"recruit_talent\": {\n",
        "                        \"goal_title\": \"For Recruiting Talent\",\n",
        "                        \"goal_icon\": \"👥\",\n",
        "                        \"strategy\": \"Attend university career fairs and industry meetups to connect with professionals.\"\n",
        "                    },\n",
        "                    \"investors\": {\n",
        "                        \"goal_title\": \"For Connecting with Investors\",\n",
        "                        \"goal_icon\": \"💼\",\n",
        "                        \"strategy\": \"Participate in venture capital conferences and pitch events.\"\n",
        "                    },\n",
        "                    \"networking\": {\n",
        "                        \"goal_title\": \"For General Networking\",\n",
        "                        \"goal_icon\": \"🌐\",\n",
        "                        \"strategy\": \"Join industry mixers and professional meetups to build relationships.\"\n",
        "                    }\n",
        "                },\n",
        "                \"specific_events\": [\n",
        "                    {\n",
        "                        \"title\": \"Industry Conference 2025\",\n",
        "                        \"meta\": \"April 2025 • San Francisco, CA • Conference\",\n",
        "                        \"description\": \"A major gathering of industry professionals where you can showcase your products and services.\",\n",
        "                        \"primary_goal\": \"find_buyers\"\n",
        "                    },\n",
        "                    {\n",
        "                        \"title\": \"Tech Expo 2025\",\n",
        "                        \"meta\": \"June 2025 • New York, NY • Expo\",\n",
        "                        \"description\": \"A large technology exhibition with opportunities for networking and partnership building.\",\n",
        "                        \"primary_goal\": \"business_partners\"\n",
        "                    },\n",
        "                    {\n",
        "                        \"title\": \"Industry Summit 2025\",\n",
        "                        \"meta\": \"September 2025 • Chicago, IL • Summit\",\n",
        "                        \"description\": \"A focused gathering of industry leaders and decision-makers.\",\n",
        "                        \"primary_goal\": \"networking\"\n",
        "                    }\n",
        "                ],\n",
        "                \"multi_factor_analysis\": {\n",
        "                    \"customer_analysis\": \"Analysis based on available information about your target market.\",\n",
        "                    \"market_growth\": \"General market trends and growth opportunities in your industry.\"\n",
        "                },\n",
        "                \"key_differentiators\": [\n",
        "                    {\"icon\": \"💡\", \"text\": \"Your unique value proposition\"},\n",
        "                    {\"icon\": \"⚡\", \"text\": \"Your technological advantages\"},\n",
        "                    {\"icon\": \"🌍\", \"text\": \"Your market reach\"},\n",
        "                    {\"icon\": \"🎭\", \"text\": \"Your innovation capabilities\"}\n",
        "                ]\n",
        "            }\n",
        "            \n",
        "            return fallback_ui_data\n",
        "                    \n",
        "        except Exception as e:\n",
        "            logger.error(f\"Error generating target events recommendation: {str(e)}\")\n",
        "            fallback_text = \"We recommend focusing on industry-specific events where you can connect with potential customers, partners, and talent.\"\n",
        "            self.target_events_text = fallback_text\n",
        "            \n",
        "            # Create a minimal UI data structure with the error fallback text\n",
        "            error_fallback_ui_data = {\n",
        "                \"target_events_text\": fallback_text,\n",
        "                \"who_to_target\": [\n",
        "                    {\"group_title\": \"Industry Professionals\", \"group_detail\": \"Focus on decision-makers in your target market\"},\n",
        "                    {\"group_title\": \"Potential Customers\", \"group_detail\": \"Connect with individuals who have a need for your product or service\"}\n",
        "                ],\n",
        "                \"event_strategies\": {\n",
        "                    \"find_buyers\": {\n",
        "                        \"goal_title\": \"For Finding Buyers/Users\",\n",
        "                        \"goal_icon\": \"💰\",\n",
        "                        \"strategy\": \"Attend industry-specific trade shows and conferences where potential customers gather.\"\n",
        "                    },\n",
        "                    \"business_partners\": {\n",
        "                        \"goal_title\": \"For Meeting Business Partners\",\n",
        "                        \"goal_icon\": \"🤝\",\n",
        "                        \"strategy\": \"Participate in conferences and integration events to connect with potential partners.\"\n",
        "                    },\n",
        "                    \"recruit_talent\": {\n",
        "                        \"goal_title\": \"For Recruiting Talent\",\n",
        "                        \"goal_icon\": \"👥\",\n",
        "                        \"strategy\": \"Attend university career fairs and industry meetups to connect with professionals.\"\n",
        "                    },\n",
        "                    \"investors\": {\n",
        "                        \"goal_title\": \"For Connecting with Investors\",\n",
        "                        \"goal_icon\": \"💼\",\n",
        "                        \"strategy\": \"Participate in venture capital conferences and pitch events.\"\n",
        "                    },\n",
        "                    \"networking\": {\n",
        "                        \"goal_title\": \"For General Networking\",\n",
        "                        \"goal_icon\": \"🌐\",\n",
        "                        \"strategy\": \"Join industry mixers and professional meetups to build relationships.\"\n",
        "                    }\n",
        "                },\n",
        "                \"specific_events\": [\n",
        "                    {\n",
        "                        \"title\": \"Industry Conference 2025\",\n",
        "                        \"meta\": \"April 2025 • San Francisco, CA • Conference\",\n",
        "                        \"description\": \"A major gathering of industry professionals where you can showcase your products and services.\",\n",
        "                        \"primary_goal\": \"find_buyers\"\n",
        "                    },\n",
        "                    {\n",
        "                        \"title\": \"Tech Expo 2025\",\n",
        "                        \"meta\": \"June 2025 • New York, NY • Expo\",\n",
        "                        \"description\": \"A large technology exhibition with opportunities for networking and partnership building.\",\n",
        "                        \"primary_goal\": \"business_partners\"\n",
        "                    },\n",
        "                    {\n",
        "                        \"title\": \"Industry Summit 2025\",\n",
        "                        \"meta\": \"September 2025 • Chicago, IL • Summit\",\n",
        "                        \"description\": \"A focused gathering of industry leaders and decision-makers.\",\n",
        "                        \"primary_goal\": \"networking\"\n",
        "                    }\n",
        "                ],\n",
        "                \"multi_factor_analysis\": {\n",
        "                    \"customer_analysis\": \"Analysis based on available information about your target market.\",\n",
        "                    \"market_growth\": \"General market trends and growth opportunities in your industry.\"\n",
        "                },\n",
        "                \"key_differentiators\": [\n",
        "                    {\"icon\": \"💡\", \"text\": \"Your unique value proposition\"},\n",
        "                    {\"icon\": \"⚡\", \"text\": \"Your technological advantages\"},\n",
        "                    {\"icon\": \"🌍\", \"text\": \"Your market reach\"},\n",
        "                    {\"icon\": \"🎭\", \"text\": \"Your innovation capabilities\"}\n",
        "                ]\n",
        "            }\n",
        "            \n",
        "            return error_fallback_ui_data\n",
        "\n"
    ]
    
    # Replace the broken method with the new implementation
    lines[start_line:start_line+2] = new_implementation
    
    # Write the updated content back to the file
    with open('core/flow_controller.py', 'w') as f:
        f.writelines(lines)
    
    print("Successfully updated the generate_target_events_recommendation method")
else:
    print("Could not find the generate_target_events_recommendation method")
